version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: metaverse-app
    ports:
      - "4000:4000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
      - /app/node_modules
  seed:
    image: metaverse-app
    command: ["npm", "run", "seed"]
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - app
