# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Create .env file from GitHub Secrets (if your app expects a .env file)
    - name: Create .env file
      run: |
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "MONGO_DEV_URI=${{ secrets.MONGO_DEV_URI }}" >> .env
        echo "MONGO_TEST_URI=${{ secrets.MONGO_TEST_URI }}" >> .env


    - run: npm ci
    - run: npm run build --if-present
      env:
        NODE_ENV: production
    - run: npm test
      env:
        NODE_ENV: test
        MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI }}
